export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold tracking-tight">
        Block Theme Generator
      </h1>
      <p className="mt-4 max-w-lg text-center text-lg text-zinc-600 dark:text-zinc-400">
        Describe the WordPress block theme you want and get a
        production-ready theme package generated by AI.
      </p>
    </main>
  );
}
